### ISSUE TITLE
make install error

### ISSUE THREAD

**Issue by ghostxiu** [awegrzyn/influxdb-cxx#14]
after "cmake --build build "
when use "make install"
get a error :
make: *** No rule to make target 'install'.  Stop.
then i:
`cd build`
`make install`
new error get:
Install the project...
-- Install configuration: "RelWithDebInfo"
-- Up-to-date: /usr/local/lib/libInfluxDB.so
CMake Error at cmake_install.cmake:60 (file):
  file INSTALL cannot find "/home/windos/influxdb-cxx/include/InfluxDB".

make: *** [Makefile:86: install] Error 1

**Comment by awegrzyn** [comment]
@ghostxiu Thanks for reporting, I've fixed the docs.

**Comment by r00sta** [comment]
The use of _-C build_ does not fix the error

> file INSTALL cannot find "/DIR/influxdb-cxx/include/InfluxDB"

**Comment by r00sta** [comment]
Fixed the issue by modifying the generated [cmake_install.cmake](https://github.com/awegrzyn/influxdb-cxx/files/3232921/cmake_install.cmake.txt) script - line 60

> file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include" TYPE DIRECTORY FILES "/root/influxdb-cxx/include/InfluxDB")

 modified it to

> file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include" TYPE DIRECTORY FILES "/root/influxdb-cxx/include/InfluxDB.h")

**Comment by awegrzyn** [comment]
@r00sta You can customise your install directory by passing `-DCMAKE_INSTALL_PREFIX` to the `cmake` call.
