### ISSUE TITLE
make build error

### ISSUE THREAD

**Issue by FreedomPointer** [awegrzyn/influxdb-cxx#16]
after "cmake -H. -Bbuild"
when use "cmake --build build"
get a error :
/usr/local/include/boost/test/unit_test.hpp:63: undefined reference to `boost::unit_test::unit_test_main(bool (*)(), int, char**)'
collect2: error: ld returned 1 exit status
CMakeFiles/testFactory.dir/build.make:85: recipe for target 'bin/testFactory' failed
make[2]: *** [bin/testFactory] Error 1
CMakeFiles/Makefile2:109: recipe for target 'CMakeFiles/testFactory.dir/all' failed
make[1]: *** [CMakeFiles/testFactory.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
**I did followed the requirements**

**Comment by awegrzyn** [comment]
Could you provide me with your environment details?
OS, compiler version, boost version.
Thanks

**Comment by FreedomPointer** [comment]
OS:
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"

Compiler version:
g++ (Ubuntu 7.4.0-1ubuntu1~18.04) 7.4.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

boost version:1.7

cmake version 3.14.4
CMake suite maintained and supported by Kitware (kitware.com/cmake).

**Comment by FreedomPointer** [comment]
All messages are here that compiler output

**sudo make -C build install**
make: Entering directory '/home/mingming/Desktop/influxdb-cxx/build'
make[1]: Entering directory '/home/mingming/Desktop/influxdb-cxx/build'
make[2]: Entering directory '/home/mingming/Desktop/influxdb-cxx/build'
Scanning dependencies of target InfluxDB
make[2]: Leaving directory '/home/mingming/Desktop/influxdb-cxx/build'
make[2]: Entering directory '/home/mingming/Desktop/influxdb-cxx/build'
[ 11%] Building CXX object CMakeFiles/InfluxDB.dir/src/InfluxDB.cxx.o
[ 22%] Building CXX object CMakeFiles/InfluxDB.dir/src/Point.cxx.o
[ 33%] Building CXX object CMakeFiles/InfluxDB.dir/src/InfluxDBFactory.cxx.o
[ 44%] Building CXX object CMakeFiles/InfluxDB.dir/src/UDP.cxx.o
[ 55%] Building CXX object CMakeFiles/InfluxDB.dir/src/UnixSocket.cxx.o
[ 66%] Building CXX object CMakeFiles/InfluxDB.dir/src/HTTP.cxx.o
[ 77%] Linking CXX shared library lib/libInfluxDB.so
make[2]: Leaving directory '/home/mingming/Desktop/influxdb-cxx/build'
[ 77%] Built target InfluxDB
make[2]: Entering directory '/home/mingming/Desktop/influxdb-cxx/build'
**Scanning dependencies of target testFactory**
make[2]: Leaving directory '/home/mingming/Desktop/influxdb-cxx/build'
make[2]: Entering directory '/home/mingming/Desktop/influxdb-cxx/build'
[ 88%] Building CXX object CMakeFiles/testFactory.dir/test/testFactory.cxx.o
[100%] Linking CXX executable bin/testFactory
CMakeFiles/testFactory.dir/test/testFactory.cxx.o: In function `main':
/usr/local/include/boost/test/unit_test.hpp:63: undefined reference to `boost::unit_test::unit_test_main(bool (*)(), int, char**)'
collect2: error: ld returned 1 exit status
CMakeFiles/testFactory.dir/build.make:85: recipe for target 'bin/testFactory' failed
make[2]: *** [bin/testFactory] Error 1
make[2]: Leaving directory '/home/mingming/Desktop/influxdb-cxx/build'
CMakeFiles/Makefile2:109: recipe for target 'CMakeFiles/testFactory.dir/all' failed
make[1]: *** [CMakeFiles/testFactory.dir/all] Error 2
make[1]: Leaving directory '/home/mingming/Desktop/influxdb-cxx/build'
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
make: Leaving directory '/home/mingming/Desktop/influxdb-cxx/build'
