### ISSUE TITLE
Bad performance of writing to InfluxDB

### ISSUE THREAD

**Issue by michalspondr** [awegrzyn/influxdb-cxx#19]
I'm experiencing a bad performance using the influxdb-cxx. Here is the simple program I am using to test performance. In this script I am trying to insert 54M of lines in batch of 15000 items.
https://gist.github.com/michalspondr/1635e968d1e50c0c10fabe238e11f6b3

The performance of this program is very low, it takes hours to insert 54 elements, InfluxDB-python script is much faster than that. I can not tell where is the problem. CPU is not loaded, InfluxDB process reaches 30% CPU peak.

**Comment by awegrzyn** [comment]
Indeed your measurements were correct, sorry you had to wait so long for a fix
