### ISSUE TITLE
Writing values with their own timestamps.

### ISSUE THREAD

**Issue by lss4** [awegrzyn/influxdb-cxx#30]
I'm going to write values with their own timestamps to the database. These may be current data values, or historical data values.

However, it seems the Point class has its timestamp [hardcoded to current timestamp](https://github.com/awegrzyn/influxdb-cxx/blob/92c38b06f9042bc924eb2991fa1c7fa5657eac27/src/Point.cxx#L19). As such, it doesn't appear to be possible to use the value's own timestamp at the moment.

Is it possible to remove this restriction and allow user to specify timestamp manually? After all, the static function used to get current timestamp is publicly accessible.

**Comment by maurodelazeri** [comment]
yea... we need to be able to set a specific timestmap, got the same problem here
