### ISSUE TITLE
my compiler cann't compile code in Point.cxx:28

### ISSUE THREAD

**Issue by FlameAlpha** [awegrzyn/influxdb-cxx#31]
In point.cxx file, there are invalid operands。
![image](https://user-images.githubusercontent.com/26116344/64147459-e79d5a00-ce52-11e9-940f-32226337f666.png)
the error log is followed
./src/Point.cxx:27: error: invalid operands to binary expression ('std::stringstream' (aka 'basic_stringstream<char, char_traits<char>, allocator<char> >') and 'std::string_view' (aka 'basic_string_view<char>'))

After I used name.data() to handle it, the porgram throw a unhandled exception from ucrtbased.dll 

![image](https://user-images.githubusercontent.com/26116344/64149055-86c45080-ce57-11e9-8304-fa5d1298d6f9.png)
I don't know if it's because I don't have a local database

**Comment by awegrzyn** [comment]
Could you please describe your env? OS, compiler, etc? I need to reproduce it.

**Comment by FlameAlpha** [comment]
> Could you please describe your env? OS, compiler, etc? I need to reproduce it.

thank you, I compiled this on the Windows 10 platform, the compiler is MSVC 2017 x64，C++ 17 
And when I set up my local database Settings,no longer throws exceptions
