### ISSUE TITLE
A coredump problem

### ISSUE THREAD

**Issue by sherimao** [awegrzyn/influxdb-cxx#35]
```
Program terminated with signal 6, Aborted.
#0  0x00007f1cd458e1f7 in raise () from /lib64/libc.so.6
(gdb) bt
#0  0x00007f1cd458e1f7 in raise () from /lib64/libc.so.6
#1  0x00007f1cd458f8e8 in abort () from /lib64/libc.so.6
#2  0x00007f1cd4e959d5 in __gnu_cxx::__verbose_terminate_handler() () from /lib64/libstdc++.so.6
#3  0x00007f1cd4e93946 in ?? () from /lib64/libstdc++.so.6
#4  0x00007f1cd4e92909 in ?? () from /lib64/libstdc++.so.6
#5  0x00007f1cd4e93574 in __gxx_personality_v0 () from /lib64/libstdc++.so.6
#6  0x00007f1cd492c903 in ?? () from /lib64/libgcc_s.so.1
#7  0x00007f1cd492ce37 in _Unwind_Resume () from /lib64/libgcc_s.so.1
#8  0x00007f1cd09525c9 in _M_dispose (__a=..., this=<optimized out>) at /opt/rh/devtoolset-7/root/usr/include/c++/7/bits/basic_string.h:3234
#9  ~basic_string (this=<optimized out>, __in_chrg=<optimized out>) at /opt/rh/devtoolset-7/root/usr/include/c++/7/bits/basic_string.h:3621
#10 influxdb::InfluxDB::flushBuffer (this=0x7f1cc4002ab0) at /tmp/influxdb-cxx-master/src/InfluxDB.cxx:28
#11 0x00007f1cd09526cd in influxdb::InfluxDB::~InfluxDB (this=0x7f1cc4002ab0, __in_chrg=<optimized out>)
    at /tmp/influxdb-cxx-master/src/InfluxDB.cxx:47
#12 0x00007f1cd0e7b3a9 in operator() (this=<optimized out>, __ptr=0x7f1cc4002ab0) at /opt/rh/devtoolset-7/root/usr/include/c++/7/bits/unique_ptr.h:78
#13 ~unique_ptr (this=<synthetic pointer>, __in_chrg=<optimized out>) at /opt/rh/devtoolset-7/root/usr/include/c++/7/bits/unique_ptr.h:268
#14 foo (systemName="xx", base=base@entry=0x196b090) at statistics/statistics.cpp:41
#15 0x00007f1cd0e7b8e7 in crontab (ptr=0x196b090) at statistics/statistics.cpp:79
#16 0x00007f1cd5bebe25 in start_thread () from /lib64/libpthread.so.0
#17 0x00007f1cd465135d in clone () from /lib64/libc.so.6
```

I change InfluxDB.cxx:
InfluxDB::InfluxDB(std::unique_ptr<Transport> transport) :
  mTransport(std::move(transport))
{
    // add this 4 lines
    mBuffering = false;
    mBuffer.clear();
    mBufferSize = 0;
    mGlobalTags = "";
}
And it's fixed

==============================
Reason:
Batch write will call flushBuffer() which may throw exception in the destructor.
If you use batch write, please call flushBuffer() manually and catch the exception.(In the old version, mBuffering is uninited, which may be a random value)

@awegrzyn Exception shouldn't be thrown in destructor. Can you change it?
Another problem, if we use batch write(mBuffering=true), but there is nothing in mBuffer, flushBuffer() will still transmit an empty string. I think it's not necessary.
You can change it like this:
void InfluxDB::flushBuffer() {
  if (!mBuffering) {
    return;
  }
  std::string stringBuffer;
  for (const auto &i : mBuffer) {
    stringBuffer+= i + "\n";
  }
  mBuffer.clear();
  // no need to send an empty string
  if (!stringBuffer.empty()) {
    transmit(std::move(stringBuffer));
  }
}

**Comment by awegrzyn** [comment]
Could you please provide a code sample to reproduce that?

**Comment by sherimao** [comment]
> Could you please provide a code sample to reproduce that?

Just simple usage. The probability of occurrence is very small.
Anyway, it's better to init class members.
```
std::unique_ptr<influxdb::InfluxDB> influxdb;
influxdb = influxdb::InfluxDBFactory::Get("http://xx");
influxdb->write(
    influxdb::Point{"x"}
        .addTag("x", "x")
        .addField("xx", 1)
);
```

**Comment by awegrzyn** [comment]
https://github.com/awegrzyn/influxdb-cxx/pull/43
