### ISSUE TITLE
Header install is installing in odd path

### ISSUE THREAD

**Issue by mvphilip** [awegrzyn/influxdb-cxx#37]
Hello, This statement:

install(DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/include DESTINATION "${CMAKE_INSTALL_INCLUDEDIR}")

installs in an odd location. 

-- Installing: /usr/local/include/include
-- Installing: /usr/local/include/include/InfluxDB.h
-- Installing: /usr/local/include/include/InfluxDBFactory.h
-- Installing: /usr/local/include/include/Point.h
-- Installing: /usr/local/include/include/Transport.h

There is an extra include there. The recommended approach seems to be:

file(GLOB PHEADERS ${CMAKE_CURRENT_SOURCE_DIR}/include/*.h)
set_target_properties(InfluxDB PROPERTIES PUBLIC_HEADER "${PHEADERS}")
# Install library
install(TARGETS InfluxDB
  EXPORT InfluxDBTargets
  LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
  ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}
  RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}
  PUBLIC_HEADER DESTINATION "${CMAKE_INSTALL_INCLUDEDIR}"
)
This installs here:
-- Up-to-date: /usr/local/include/InfluxDB.h
-- Up-to-date: /usr/local/include/InfluxDBFactory.h
-- Up-to-date: /usr/local/include/Point.h
-- Up-to-date: /usr/local/include/Transport.h

Would you consider making the above change?

Thanks,

-mp

**Comment by awegrzyn** [comment]
Thanks for reporting, there's actually simpler fix, see: https://github.com/awegrzyn/influxdb-cxx/pull/39

**Comment by mvphilip** [comment]
Thanks a lot. That will work.

-mp
