### ISSUE TITLE
forward slash in example 

### ISSUE THREAD

**Issue by mvphilip** [awegrzyn/influxdb-cxx#40]
Hello In the example given:

auto influxdb = influxdb::InfluxDBFactory::Get("http://localhost:8086/?db=test");

The http query for write is formatted by 

writeUrl.insert(url.find("?"), "/write");

and the final curl query would be

http://localhost:8086//write?db=test

Notice the two forward slashes before the write post "//write" 
With libcurl/standalone curl 7.64.0 and influx 1.7.9-1 on ubuntu this double slash query will fail.
I can show an example with ping:

curl -v "http://localhost:8086//ping"

*   Trying 127.0.0.1...
* TCP_NODELAY set
* Expire in 150000 ms for 3 (transfer 0x5555555c75c0)
* Expire in 200 ms for 4 (transfer 0x5555555c75c0)
* Connected to localhost (127.0.0.1) port 8086 (#0)
> GET //ping HTTP/1.1
> Host: localhost:8086
> User-Agent: curl/7.64.0
> Accept: */*
>
**< HTTP/1.1 404 Not Found**
< Content-Type: text/plain; charset=utf-8
< X-Content-Type-Options: nosniff
< X-Influxdb-Build: OSS
< X-Influxdb-Version: 1.7.9
< Date: Wed, 13 Nov 2019 21:07:25 GMT
< Content-Length: 19

Whereas single slash is fine:

curl -v "http://localhost:8086/ping"

*   Trying 127.0.0.1...
* TCP_NODELAY set
* Expire in 149999 ms for 3 (transfer 0x5555555c75c0)
* Expire in 200 ms for 4 (transfer 0x5555555c75c0)
* Connected to localhost (127.0.0.1) port 8086 (#0)
> GET /ping HTTP/1.1
> Host: localhost:8086
> User-Agent: curl/7.64.0
> Accept: */*
>
< HTTP/1.1 204 No Content
< Content-Type: application/json
< Request-Id: b9a1d82a-0659-11ea-8016-0242c0a8b002
< X-Influxdb-Build: OSS
< X-Influxdb-Version: 1.7.9
< X-Request-Id: b9a1d82a-0659-11ea-8016-0242c0a8b002
< Date: Wed, 13 Nov 2019 21:08:22 GMT
 
So could you let me know what version of influx you are using for the example? 
In my case I can get around this problem easy enough. But maybe something like

  std::string writeUrl = url;
  auto url_bslash = writeUrl.find("/?");
  if (url_bslash != std::string::npos) {
	writeUrl.replace(url_bslash, 2, "/write?");
  } else {
	writeUrl.insert(url.find("?"), "/write");
  }

For the future?

thanks,

-mp

**Comment by awegrzyn** [comment]
Thanks for the report, so this part of code is not yet tagged (but already in master). I'll definitely fix what you reported before tagging new version also I'll try to increase test coverage.
