### ISSUE TITLE
Better diagnostics/exception handling

### ISSUE THREAD

**Issue by mvphilip** [awegrzyn/influxdb-cxx#44]
Hi, The current api does not have any diagnostics in terms of failure to connect. For example if the db name is wrong etc. I have prototyped at least a connect method that can create a DB if it doesn't exist and plan to add several other exception handlers. But I am not sure if you have plans to address this and/or how you will do so. 

I didnt want to get too far in a fork without at least asking if you have said plans/and or if you would accept PRs. For the connect method at least I had to touch Transport/HTTP as well as InfluxDB. 

If you would let me know if you have interest in this please let me know.

Much appreciated.

-mp

**Comment by awegrzyn** [comment]
Hi, all PR with fixes, new features and improvements are highly welcome!
I work on this project in sprints every month, I plan to progress on it next during Christmas break.
