### ISSUE TITLE
Is there a cross-platform plan for this project?

### ISSUE THREAD

**Issue by HarryColin** [awegrzyn/influxdb-cxx#45]

**Comment by awegrzyn** [comment]
Could you elaborate on your questions? Currently you can I've tested it on CentOS, Ubuntu and macOS.

**Comment by HarryColin** [comment]
> Could you elaborate on your questions? Currently you can I've tested it on CentOS, Ubuntu and macOS.

for example windows? I have tested on CentOS. Thank for your help.

**Comment by awegrzyn** [comment]
Regarding Windows support the conversation will continue in https://github.com/awegrzyn/influxdb-cxx/issues/65
