### ISSUE TITLE
Possible to separate Point definition and db->write call ?

### ISSUE THREAD

**Issue by jguiban** [awegrzyn/influxdb-cxx#47]
Could you please tell me if it is possible to separate the "Point" definition and the db->write() call:
 
I did not find it in the exemples and the following test code I wrote failed to compile:

```
 influxdb = influxdb::InfluxDBFactory::Get("http:/127.0.0.1/?db=dbtest");
 Point point = Point{"test"}.addField("value", 10);
 point.addField("value2", 20);
 influxdb->write(point);
```

decoder.cpp:89:18: error: ‘class std::unique_ptr<influxdb::InfluxDB>’ has no member named ‘write’
         influxdb.write(point);
                  ^~~~~

**Comment by awegrzyn** [comment]
@jguiban Yes, of course, just use `influxdb->write(std::move(point));`

**Comment by jguiban** [comment]
Many thanks @awegrzyn .
