### ISSUE TITLE
Got C4996 problem when using it into my project

### ISSUE THREAD

**Issue by wzf-cn** [awegrzyn/influxdb-cxx#50]
Hi,
The example could be run correctly along in a project. But when I include this code into my project, the error came out.

    c4996 'inet_addr':Use inet_pton() or InetPton() instead or define _WINSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings

I had followed the [solution in the stackoverflow](https://stackoverflow.com/questions/36683785/inet-addr-use-inet-pton-or-inetpton-instead-or-define-winsock-deprecated/47397620), included the "Ws2tcpip.h" and changed the line 127 and line 205 in the influxdb.hpp as follows, then the program returned -3.
```cpp
// For line 127
InetPton(AF_INET, (PCWSTR)(host.c_str()), &addr.sin_addr.s_addr);
if (addr.sin_addr.s_addr == INADDR_NONE) return -1;
```

```cpp
// For line 205
InetPton(AF_INET, (PCWSTR)(si.host_.c_str()), &addr.sin_addr.s_addr);
if (addr.sin_addr.s_addr == INADDR_NONE) return -1;
```

**Comment by awegrzyn** [comment]
Hi,
Unfortunately, there's no Windows support so far, I plan to add it soon.

**Comment by awegrzyn** [comment]
https://github.com/awegrzyn/influxdb-cxx/issues/65
