### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by iwita** [awegrzyn/influxdb-cxx#55]
Hello, 

I am trying to use the library in my application, using the first example in the README file:
`auto influxdb = influxdb::InfluxDBFactory::Get("http://localhost:8086/?db=test");
influxdb->write(Point{"test"}
  .addField("value", 10)
  .addTag("host", "localhost")
);`
When I am compiling my application I have the following errors occuring.
Any help would be appreciated

`
In file included from /usr/local/include/InfluxDB.h:15:0,
                 from myapp.cpp:62:
/usr/local/include/Point.h:27:13: error: expected ‘;’ at end of member declaration
     Point&& addTag(std::string_view key, std::string_view value);
             ^~~~~~
/usr/local/include/Point.h:27:37: error: expected ‘)’ before ‘key’
     Point&& addTag(std::string_view key, std::string_view value);
                                     ^~~
/usr/local/include/Point.h:30:13: error: expected ‘;’ at end of member declaration
     Point&& addField(std::string_view name, std::variant<int, long long int, std::string, double> value);
             ^~~~~~~~
/usr/local/include/Point.h:30:39: error: expected ‘)’ before ‘name’
     Point&& addField(std::string_view name, std::variant<int, long long int, std::string, double> value);
                                       ^~~~
/usr/local/include/Point.h:52:10: error: ‘variant’ in namespace ‘std’ does not name a template type
     std::variant<long long int, std::string, double> mValue;
          ^~~~~~~
In file included from myapp.cpp:62:0:
/usr/local/include/InfluxDB.h:52:28: error: ‘std::string_view’ has not been declared
     void addGlobalTag(std::string_view name, std::string_view value);
                            ^~~~~~~~~~~
/usr/local/include/InfluxDB.h:52:51: error: ‘std::string_view’ has not been declared
     void addGlobalTag(std::string_view name, std::string_view value);
`

and 

` error: ‘Point’ was not declared in this scope
     influxdb->write(Point{"test"}.addField("value", 10).addTag("host", "localhost"));
`

**Comment by iwita** [comment]
By alternating the switch from -std=c++11 to -std=c++17, I got rid of the first errors and I ended up with only the last one remaining.

**Comment by awegrzyn** [comment]
Hi, this is not fully working example as it's missing `using` declaration.
In addition, I'd recommend using CMake in your project so you don't need to handle `-std` switches manually.
