### ISSUE TITLE
Support for c++11

### ISSUE THREAD

**Issue by tuxroger** [awegrzyn/influxdb-cxx#62]
Hi, are you planning any version that can be built in c++11?
Thanks,
Roger.

**Comment by awegrzyn** [comment]
Hi,
As Point class is based on `std::variant` it would require major changes to make it compatible with C++11 standard, therefore there's no plan to do so.
Cheers,
Adam

**Comment by tuxroger** [comment]
Thanks for the response and sorry for the late reply! :)
Roger.
