### ISSUE TITLE
Time format is not valid

### ISSUE THREAD

**Issue by sinestic** [awegrzyn/influxdb-cxx#63]
https://github.com/awegrzyn/influxdb-cxx/blob/07a2ab160807e573969851add17e38e16d3323d1/src/InfluxDB.cxx#L107

In the function std::get_time, the formats %F and %T seems to be not implemented yet.

https://en.cppreference.com/w/cpp/io/manip/get_time

**Comment by awegrzyn** [comment]
Indeed it seems to work on macOS only, lemme take a look at it.
