### ISSUE TITLE
Incorrect format specifiers

### ISSUE THREAD

**Issue by suryakalpo** [awegrzyn/influxdb-cxx#69]
https://github.com/awegrzyn/influxdb-cxx/blob/0bb9a05e4205a788517a7c27790c8e6f50a5575f/src/InfluxDB.cxx#L107

I believe the format specifiers that are used with `std::get_time` are actually only valid with `std::strftime`. I'm unable to find concrete documentation to prove that `strftime()` and `strptime()` don't share all the specifiers in format string. However, I can illustrate the difference through an example:

```
$ cat sample.cpp
#include <sstream>
#include <iostream>
#include <chrono>
#include <ctime>
#include <iomanip>

int main(int argc, char** argv)
{
    std::stringstream ss("2020-03-18T09:11:25Z");

    std::cout << ss.str() << "\n";
    std::tm tm = {};

    #ifdef __FIX__
    ss >> std::get_time(&tm, "%Y-%m-%dT%H:%M:%SZ");
    #else
    ss >> std::get_time(&tm, "%FT%TZ");
    #endif

    tm.tm_isdst = -1;
    auto tstamp = std::chrono::system_clock::from_time_t(std::mktime(&tm));
    auto t = std::chrono::system_clock::to_time_t(tstamp);
    std::cout << "Timestamp: " << std::ctime(&t) << "\n";

    return 0;
}

$ g++8 -g -std=c++17 sample.cpp -o sample
$ ./sample
2020-03-18T09:11:25Z
Timestamp: Wed Dec 31 18:59:59 1969

$ g++8 -g -std=c++17 -D __FIX__ sample.cpp -o sample
$ ./sample
2020-03-18T09:11:25Z
Timestamp: Wed Mar 18 09:11:25 2020

$ uname -a
FreeBSD ftlvssarkFreeBSD 11.1-RELEASE FreeBSD 11.1-RELEASE #0 r321309: Fri Jul 21 02:08:28 UTC 2017     root@releng2.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64

```

Another issue here is that `std::get_time` doesn't set `tm::is_dst`, so I think we need to set it explicitly to -1, otherwise it remains at 0 and then `std::mktime` interprets that as if DST is in effect.

**Comment by awegrzyn** [comment]
Hi,
Indeed you are right and thanks for providing fix. I opened a PR with timestamp check and it failed: https://github.com/awegrzyn/influxdb-cxx/pull/68/files
I'll definitely add this fix this week!

**Comment by awegrzyn** [comment]
It works, thanks you !
