### ISSUE TITLE
Help: Http::query error, Status code 404

### ISSUE THREAD

**Issue by tesion99** [awegrzyn/influxdb-cxx#79]
I use the client to test write/query function of influxdb-cxx ，compiled with macro INFLUXDB_WITH_BOOST.
It wrote successfully, but when I query data from db, it throw an exception as follow:
 **influx-cxx [HTTP::query]: Status code: 404**
I find the Http::query use **GET** to get the data, then I use command like this **curl -i -XPOST 'http://localhost:8086/query?db=testDB' --data-urlencode "q=SELECT * FROM weather"**，it works.
Influxdb 1.8 doesn't support HTTP/GET??? Can anbody give me some help???
Code like this:
```cpp
 auto influxdb = influxdb::InfluxDBFactory::Get("http://localhost:8086/?db=testDB");
    influxdb->write(influxdb::Point{"weather"}
        .addTag("altitude", "3000")
        .addTag("area", "North")
        .addField("temp", 100)
        .addField("humidity", 258)
    );

    printf("Query From influxDB ...\n");
    auto idb = influxdb::InfluxDBFactory::Get("http://localhost:8086/?db=testDB");
    try {
        idb->query("SELECT * FROM weather");
    } catch (influxdb::InfluxDBException &e) {
        std::cout << e.what() << std::endl;
    }
```

**Comment by suryakalpo** [comment]
The URL path specified in your query is not the same as what was used in curl. For what it's worth, the path used in curl is correct as per the default InfluxDB directory structure.
The URL path should be `"http://localhost:8086/query?db=testDB"`

**Comment by tesion99** [comment]
@suryakalpo Thanks for your reply. I debug in the source code，when we do some query with http，the HTTP transport model will insert "**/query**" in url，the code does't check more details.
So when I use url http://localhost:8086/?db=testDB，http model changes it like **http://localhost:8086//query?db=testDB**, this is the bug.
